app.name: learning-redis

server:
  port: 8081
  servlet:
    context-path: /${app.name}

spring:
  application.name: ${app.name}
  mvc:
    date-format: "yyyy-MM-dd HH:mm:ss"
    dispatch-trace-request: true
  jackson:
    default-property-inclusion: NON_NULL
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
  redis:
    host: 192.168.52.129
    database: 0
    timeout: 50000