app.name: learning-example

server:
  port: 8083
  servlet:
    context-path: /${app.name}

spring:
  application.name: ${app.name}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    serialization.WRITE_DATES_AS_TIMESTAMPS: false

common:
  date-format:
    enabled: true
#    date-pattern:
#    local-date-pattern: yyyy/MM/dd
#    local-date-time-pattern:
#    local-time-pattern:
